spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kotlin?useTimeZone=true&serverTimeZone=UTC&useLegacyDate
    username: docker
    password: docker
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
spring-doc:
  paths-to-match:
    - /**
  swagger-ui:
    use-root-path: true