CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_name VARCHAR(255),
   full_name VARCHAR(255),
   password VARCHAR(255),
   account_non_expired BOOLEAN,
   account_non_locked BOOLEAN,
   credentials_non_expired BOOLEAN,
   enabled BOOLEAN,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT uc_users_user_name UNIQUE (user_name);